/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "ai-system-design",
  "title": "AI System Design for Staff+ Interviews",
  "sections": [
    {
      "n": "01",
      "title": "Foundations",
      "lessons": [
        {
          "title": "LLM Basics",
          "href": "lessons/0000-llm-basics.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Retrieval",
      "lessons": [
        {
          "title": "RAG and Retrieval",
          "href": "lessons/0001-rag-and-retrieval.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Architecture",
      "lessons": [
        {
          "title": "AI System Architecture",
          "href": "lessons/0002-ai-system-architecture.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Economics",
      "lessons": [
        {
          "title": "Cost and Performance",
          "href": "lessons/0003-cost-and-performance.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Quality",
      "lessons": [
        {
          "title": "Evaluation and Quality",
          "href": "lessons/0004-evaluation-and-quality.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Operations",
      "lessons": [
        {
          "title": "Reliability and Security",
          "href": "lessons/0005-reliability-and-security.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
