/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "staff-ai",
  "title": "The Staff AI Engineer",
  "sections": [
    {
      "n": "01",
      "title": "Evidence",
      "lessons": [
        {
          "title": "Reading the Claim",
          "href": "lessons/0000-reading-the-claim.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Restraint",
      "lessons": [
        {
          "title": "Should This Be an AI System at All",
          "href": "lessons/0001-should-this-be-an-ai-system.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Shape",
      "lessons": [
        {
          "title": "The Shape of the System",
          "href": "lessons/0002-the-shape-of-the-system.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Knowledge",
      "lessons": [
        {
          "title": "Where the Knowledge Comes From",
          "href": "lessons/0003-where-the-knowledge-comes-from.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Proof",
      "lessons": [
        {
          "title": "Proving It Works",
          "href": "lessons/0004-proving-it-works.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Money",
      "lessons": [
        {
          "title": "What It Costs",
          "href": "lessons/0005-what-it-costs.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Authority",
      "lessons": [
        {
          "title": "The Blast Radius",
          "href": "lessons/0006-the-blast-radius.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Supply",
      "lessons": [
        {
          "title": "Model Supply Is a Dependency",
          "href": "lessons/0007-model-supply-is-a-dependency.html"
        }
      ]
    },
    {
      "n": "09",
      "title": "Organisation",
      "lessons": [
        {
          "title": "Carrying the Organisation",
          "href": "lessons/0008-carrying-the-organisation.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    },
    {
      "title": "Decision Record",
      "href": "reference/decision-record.html"
    },
    {
      "title": "Claim Audit",
      "href": "reference/claim-audit.html"
    }
  ]
};
