/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "ai-engineering",
  "title": "End-to-End AI Engineering",
  "sections": [
    {
      "n": "00",
      "title": "Start here",
      "lessons": [
        {
          "title": "Your demo works and you cannot prove it",
          "href": "lessons/0000-your-demo-works-and-you-cannot-prove-it.html"
        }
      ]
    },
    {
      "n": "01",
      "title": "Foundations",
      "lessons": [
        {
          "title": "The lifecycle is a loop with a measurement in it",
          "href": "lessons/0100-the-lifecycle-is-a-loop-with-a-measurement-in-it.html"
        },
        {
          "title": "The environment is a lockfile, a key and a trace",
          "href": "lessons/0110-the-environment-is-a-lockfile-a-key-and-a-trace.html"
        },
        {
          "title": "RAG is a search problem wearing a generation costume",
          "href": "lessons/0120-rag-is-a-search-problem-wearing-a-generation-costume.html"
        },
        {
          "title": "An embedding is a lossy address, not a meaning",
          "href": "lessons/0130-an-embedding-is-a-lossy-address-not-a-meaning.html"
        },
        {
          "title": "A vector index trades recall for latency, and a filter breaks it",
          "href": "lessons/0140-a-vector-index-trades-recall-for-latency.html"
        },
        {
          "title": "A RAG trace has a retrieval span, and that is where you look first",
          "href": "lessons/0150-a-rag-trace-has-a-retrieval-span.html"
        },
        {
          "title": "Measure the retrieval before the model is involved",
          "href": "lessons/0160-measure-the-retrieval-before-the-model-is-involved.html"
        },
        {
          "title": "A generation metric is a judge, and a judge needs its own eval",
          "href": "lessons/0170-a-generation-metric-is-a-judge.html"
        },
        {
          "title": "The baseline you will argue with",
          "href": "lessons/1000-the-baseline-you-will-argue-with.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Retrieval quality and context engineering",
      "lessons": [
        {
          "title": "Ingestion is a pipeline, and every chunk needs an identity",
          "href": "lessons/0200-ingestion-is-a-pipeline-and-every-chunk-needs-an-identity.html"
        },
        {
          "title": "A schema is a contract the model has to satisfy",
          "href": "lessons/0210-a-schema-is-a-contract-the-model-has-to-satisfy.html"
        },
        {
          "title": "Chunking is a boundary decision, and the boundary is where meaning is lost",
          "href": "lessons/0220-chunking-is-a-boundary-decision-and-the-boundary-is-where-meaning-is-lost.html"
        },
        {
          "title": "A chunk that cannot say where it came from cannot be found",
          "href": "lessons/0230-a-chunk-that-cannot-say-where-it-came-from-cannot-be-found.html"
        },
        {
          "title": "The window is an attention budget, not a container",
          "href": "lessons/0240-the-window-is-an-attention-budget-not-a-container.html"
        },
        {
          "title": "A prompt is a versioned artefact with a name",
          "href": "lessons/0250-a-prompt-is-a-versioned-artefact-with-a-name.html"
        },
        {
          "title": "Two rankings beat one, and RRF is the cheapest way to add them",
          "href": "lessons/0260-two-rankings-beat-one-and-rrf-is-the-cheapest-way-to-add-them.html"
        },
        {
          "title": "A reranker is a second, more expensive opinion on twenty documents",
          "href": "lessons/0270-a-reranker-is-a-second-more-expensive-opinion-on-twenty-documents.html"
        },
        {
          "title": "The document you retrieved is untrusted input",
          "href": "lessons/0280-the-document-you-retrieved-is-untrusted-input.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Agents and agentic systems",
      "lessons": [
        {
          "title": "Five shapes, and the one that loops",
          "href": "lessons/0300-five-shapes-and-the-one-that-loops.html"
        },
        {
          "title": "A loop you did not write is still a loop you must stop",
          "href": "lessons/0310-a-loop-you-did-not-write-is-still-a-loop-you-must-stop.html"
        },
        {
          "title": "A tool call is the only verb an agent has",
          "href": "lessons/0320-a-tool-call-is-the-only-verb-an-agent-has.html"
        },
        {
          "title": "A failed tool call is a result, not an exception",
          "href": "lessons/0330-a-failed-tool-call-is-a-result-not-an-exception.html"
        },
        {
          "title": "Memory is four stores with four lifetimes",
          "href": "lessons/0340-memory-is-four-stores-with-four-lifetimes.html"
        },
        {
          "title": "Give the agent a memory it maintains, and a path it cannot escape",
          "href": "lessons/0350-give-the-agent-a-memory-it-maintains.html"
        },
        {
          "title": "Reflection works when the feedback comes from outside",
          "href": "lessons/0360-reflection-works-when-the-feedback-comes-from-outside.html"
        },
        {
          "title": "Grade the path, not only the answer",
          "href": "lessons/0370-grade-the-path-not-only-the-answer.html"
        },
        {
          "title": "The agent that knows when to stop",
          "href": "lessons/1020-the-agent-that-knows-when-to-stop.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "From basic to agentic RAG",
      "lessons": [
        {
          "title": "Retrieval becomes a tool the model decides to call",
          "href": "lessons/0400-retrieval-becomes-a-tool-the-model-decides-to-call.html"
        },
        {
          "title": "A retrieval you do not trust is one you can correct",
          "href": "lessons/0410-a-retrieval-you-do-not-trust-is-one-you-can-correct.html"
        },
        {
          "title": "A pause is a state you saved, not a thread you blocked",
          "href": "lessons/0420-a-pause-is-a-state-you-saved.html"
        },
        {
          "title": "A thumb down is a row in the golden set",
          "href": "lessons/0430-a-thumb-down-is-a-row-in-the-golden-set.html"
        },
        {
          "title": "Your RAG app is a host, and its best source is one you did not write",
          "href": "lessons/0440-your-rag-app-is-a-host.html"
        },
        {
          "title": "A deep research agent is a retrieval loop with a citation contract",
          "href": "lessons/0450-a-deep-research-agent-is-a-retrieval-loop.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Multi-agent systems",
      "lessons": [
        {
          "title": "The second agent is a cost before it is a capability",
          "href": "lessons/0500-the-second-agent-is-a-cost-before-it-is-a-capability.html"
        },
        {
          "title": "Delegation is a tool call",
          "href": "lessons/0510-delegation-is-a-tool-call.html"
        },
        {
          "title": "Planning is a ledger the orchestrator rewrites",
          "href": "lessons/0520-planning-is-a-ledger-the-orchestrator-rewrites.html"
        },
        {
          "title": "Shared state is what they actually disagree about",
          "href": "lessons/0530-shared-state-is-what-they-actually-disagree-about.html"
        },
        {
          "title": "An agent that is not a tool",
          "href": "lessons/0540-an-agent-that-is-not-a-tool.html"
        },
        {
          "title": "Read the trace before you touch a prompt",
          "href": "lessons/0550-read-the-trace-before-you-touch-a-prompt.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Deployment, optimization and reliability",
      "lessons": [
        {
          "title": "Four shapes for a request that takes thirty seconds",
          "href": "lessons/0600-four-shapes-for-a-request-that-takes-thirty-seconds.html"
        },
        {
          "title": "The provider is a dependency you do not own",
          "href": "lessons/0610-the-provider-is-a-dependency-you-do-not-own.html"
        },
        {
          "title": "Where the seconds go",
          "href": "lessons/0620-where-the-seconds-go.html"
        },
        {
          "title": "Four caches, and only two of them are yours",
          "href": "lessons/0630-four-caches-and-only-two-of-them-are-yours.html"
        },
        {
          "title": "Semantic caching, and the false hit you have to measure",
          "href": "lessons/0640-semantic-caching-and-the-false-hit-you-have-to-measure.html"
        },
        {
          "title": "What a prompt injection is allowed to do",
          "href": "lessons/0650-what-a-prompt-injection-is-allowed-to-do.html"
        },
        {
          "title": "CI when the unit test is a distribution",
          "href": "lessons/0660-ci-when-the-unit-test-is-a-distribution.html"
        },
        {
          "title": "Monitoring a system whose failures are quiet",
          "href": "lessons/0670-monitoring-a-system-whose-failures-are-quiet.html"
        },
        {
          "title": "Ship it",
          "href": "lessons/1050-ship-it.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Agentic AI system design",
      "lessons": [
        {
          "title": "In the field: an orchestrator and its workers",
          "href": "lessons/0700-in-the-field-an-orchestrator-and-its-workers.html"
        },
        {
          "title": "In the field: a text-to-SQL agent people actually use",
          "href": "lessons/0710-in-the-field-a-text-to-sql-agent-people-actually-use.html"
        },
        {
          "title": "Sizing a system you have not built",
          "href": "lessons/0720-sizing-a-system-you-have-not-built.html"
        },
        {
          "title": "The design review: six questions, on your own system",
          "href": "lessons/0730-the-design-review-six-questions.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Final delivery",
      "lessons": [
        {
          "title": "Three tiers of test for a system that answers differently every time",
          "href": "lessons/0800-three-tiers-of-test.html"
        },
        {
          "title": "The repository a stranger can run",
          "href": "lessons/0810-the-repository-a-stranger-can-run.html"
        },
        {
          "title": "The delivery: what replaces demo day",
          "href": "lessons/0820-the-delivery-what-replaces-demo-day.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    },
    {
      "title": "Eval Harness",
      "href": "reference/eval-harness.html"
    },
    {
      "title": "Figures",
      "href": "reference/figures.html"
    },
    {
      "title": "Troubleshooting",
      "href": "reference/troubleshooting.html"
    }
  ]
};
