/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "azure",
  "title": "Inside Azure",
  "sections": [
    {
      "n": "01",
      "title": "The lay of the land",
      "lessons": [
        {
          "title": "One door: Azure Resource Manager",
          "href": "lessons/0100-one-door-azure-resource-manager.html"
        },
        {
          "title": "The four-scope ladder",
          "href": "lessons/0101-the-four-scope-ladder.html"
        },
        {
          "title": "Regions, zones and the redundancy ladder",
          "href": "lessons/0102-regions-zones-and-the-redundancy-ladder.html"
        },
        {
          "title": "The platform map",
          "href": "lessons/0103-the-platform-map.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Compute",
      "lessons": [
        {
          "title": "The virtual machine",
          "href": "lessons/0200-the-virtual-machine.html"
        },
        {
          "title": "Who else is on the host",
          "href": "lessons/0201-who-else-is-on-the-host.html"
        },
        {
          "title": "Images and the gallery",
          "href": "lessons/0202-images-and-the-gallery.html"
        },
        {
          "title": "Holding a fleet at a size",
          "href": "lessons/0203-holding-a-fleet-at-a-size.html"
        }
      ]
    }
  ],
  "extras": []
};
