/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "cloud-comparison",
  "title": "Comparing the Four Clouds",
  "sections": [
    {
      "n": "02",
      "title": "Compute: placement, scaling, containers",
      "lessons": [
        {
          "title": "Where a workload physically lands",
          "href": "lessons/0200-where-a-workload-lands.html"
        },
        {
          "title": "Holding a fleet at a size",
          "href": "lessons/0201-holding-a-fleet-at-a-size.html"
        },
        {
          "title": "How much of the cluster you run",
          "href": "lessons/0202-how-much-of-the-cluster-you-run.html"
        },
        {
          "title": "The function and container boundary",
          "href": "lessons/0203-the-function-container-boundary.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Storage and data",
      "lessons": [
        {
          "title": "Storage: the menu is the same, the failure domain is not",
          "href": "lessons/0301-storage-four-clouds.html"
        },
        {
          "title": "Databases: pick by packaging, not by engine",
          "href": "lessons/0302-databases-four-clouds.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Analytics",
      "lessons": [
        {
          "title": "Analytics: one pipeline, four cuts",
          "href": "lessons/0401-analytics-four-clouds.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Networking, delivery and edge",
      "lessons": [
        {
          "title": "The private network",
          "href": "lessons/0500-the-private-network.html"
        },
        {
          "title": "Load balancing and the edge",
          "href": "lessons/0501-load-balancing-and-the-edge.html"
        },
        {
          "title": "DNS and domains",
          "href": "lessons/0502-dns-and-domains.html"
        },
        {
          "title": "Hybrid connectivity",
          "href": "lessons/0503-hybrid-connectivity.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Identity and access",
      "lessons": [
        {
          "title": "Workforce identity: where a grant attaches",
          "href": "lessons/0600-workforce-identity-where-a-grant-attaches.html"
        },
        {
          "title": "Machine identity: proving it without a secret",
          "href": "lessons/0601-machine-identity-proving-it-without-a-secret.html"
        },
        {
          "title": "Customer identity: the directory you build on",
          "href": "lessons/0602-customer-identity-the-directory-you-build-on.html"
        },
        {
          "title": "Secrets, keys and certificates: who holds custody",
          "href": "lessons/0603-secrets-keys-and-certificates-who-holds-custody.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Governance, tenancy and telemetry",
      "lessons": [
        {
          "title": "Hierarchy and guardrails",
          "href": "lessons/0700-hierarchy-and-guardrails.html"
        },
        {
          "title": "Policy, drift and inventory",
          "href": "lessons/0701-policy-drift-and-inventory.html"
        },
        {
          "title": "The observability stack",
          "href": "lessons/0702-observability-stack.html"
        },
        {
          "title": "The telemetry streams",
          "href": "lessons/0703-the-telemetry-streams.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Security, delivery, integration and intelligence",
      "lessons": [
        {
          "title": "The security services layer",
          "href": "lessons/0800-security-services.html"
        },
        {
          "title": "Infrastructure as code and deployment",
          "href": "lessons/0801-iac-and-deployment.html"
        },
        {
          "title": "Integration and messaging",
          "href": "lessons/0802-integration-and-messaging.html"
        },
        {
          "title": "AI and ML services",
          "href": "lessons/0803-ai-and-ml-services.html"
        }
      ]
    }
  ],
  "extras": []
};
