/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "cloud-comparison",
  "title": "Comparing the Four Clouds",
  "sections": [
    {
      "n": "02",
      "title": "Compute: placement, scaling, containers",
      "lessons": [
        {
          "title": "Where a workload physically lands",
          "href": "lessons/0200-where-a-workload-lands.html"
        },
        {
          "title": "Holding a fleet at a size",
          "href": "lessons/0201-holding-a-fleet-at-a-size.html"
        }
      ]
    }
  ],
  "extras": []
};
