/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "cloud-comparison",
  "title": "Comparing the Four Clouds",
  "sections": [
    {
      "n": "02",
      "title": "Compute: placement, scaling, containers",
      "lessons": [
        {
          "title": "Where a workload physically lands",
          "href": "lessons/0200-where-a-workload-lands.html"
        },
        {
          "title": "Holding a fleet at a size",
          "href": "lessons/0201-holding-a-fleet-at-a-size.html"
        },
        {
          "title": "How much of the cluster you run",
          "href": "lessons/0202-how-much-of-the-cluster-you-run.html"
        },
        {
          "title": "The function and container boundary",
          "href": "lessons/0203-the-function-container-boundary.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Governance, tenancy and telemetry",
      "lessons": [
        {
          "title": "Hierarchy and guardrails",
          "href": "lessons/0070-hierarchy-and-guardrails.html"
        },
        {
          "title": "Policy, drift and inventory",
          "href": "lessons/0071-policy-drift-and-inventory.html"
        },
        {
          "title": "The observability stack",
          "href": "lessons/0072-observability-stack.html"
        },
        {
          "title": "The telemetry streams",
          "href": "lessons/0073-the-telemetry-streams.html"
        }
      ]
    }
  ],
  "extras": []
};
