/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "math-for-ml",
  "title": "Mathematics for Machine Learning and Data Science",
  "sections": [
    {
      "n": "00",
      "title": "Start Here",
      "lessons": [
        {
          "title": "One line of a paper needs every module in this course",
          "href": "lessons/0000-one-line-of-a-paper.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Eigenvalues, SVD, and PCA",
      "lessons": [
        {
          "title": "Some directions a matrix only stretches",
          "href": "lessons/0060-eigenvectors-the-directions-a-matrix-does-not-turn.html"
        },
        {
          "title": "One polynomial holds every eigenvalue",
          "href": "lessons/0061-the-characteristic-equation-trace-and-determinant.html"
        },
        {
          "title": "Symmetric matrices are the well-behaved ones",
          "href": "lessons/0062-the-spectral-theorem-for-symmetric-matrices.html"
        },
        {
          "title": "A matrix is a landscape once you feed it a vector twice",
          "href": "lessons/0063-quadratic-forms-bowl-saddle-or-valley.html"
        },
        {
          "title": "The matrix version of a positive number",
          "href": "lessons/0064-positive-definiteness-and-its-eigenvalue-test.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Calculus for machine learning",
      "lessons": [
        {
          "title": "A derivative is the exchange rate between a small input change and a small output change",
          "href": "lessons/0080-derivative-as-a-limit.html"
        }
      ]
    },
    {
      "n": "→",
      "title": "The road ahead",
      "lessons": [
        {
          "title": "Every module was asking one table a different question",
          "href": "lessons/0200-one-dataset-eleven-modules.html"
        },
        {
          "title": "Two modules compute the same two numbers by different means",
          "href": "lessons/0201-three-routes-same-coefficients.html"
        },
        {
          "title": "The same slope is worthless on eight rows and decisive on twenty thousand",
          "href": "lessons/0202-what-a-coefficient-is-worth.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Notation",
      "href": "reference/notation.html"
    },
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    },
    {
      "title": "Formula Sheet",
      "href": "reference/formula-sheet.html"
    },
    {
      "title": "Datasets",
      "href": "reference/datasets.html"
    },
    {
      "title": "By Subject",
      "href": "reference/by-subject.html"
    },
    {
      "title": "Interview Index",
      "href": "reference/interview-index.html"
    },
    {
      "title": "Self Test",
      "href": "reference/self-test.html"
    }
  ]
};
