/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "math-for-ml",
  "title": "Mathematics for Machine Learning and Data Science",
  "sections": [
    {
      "n": "00",
      "title": "Start Here",
      "lessons": [
        {
          "title": "One line of a paper needs every module in this course",
          "href": "lessons/0000-one-line-of-a-paper.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Eigenvalues, SVD, and PCA",
      "lessons": [
        {
          "title": "Some directions a matrix only stretches",
          "href": "lessons/0060-eigenvectors-the-directions-a-matrix-does-not-turn.html"
        },
        {
          "title": "One polynomial holds every eigenvalue",
          "href": "lessons/0061-the-characteristic-equation-trace-and-determinant.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Notation",
      "href": "reference/notation.html"
    },
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    },
    {
      "title": "Formula Sheet",
      "href": "reference/formula-sheet.html"
    },
    {
      "title": "Datasets",
      "href": "reference/datasets.html"
    },
    {
      "title": "By Subject",
      "href": "reference/by-subject.html"
    },
    {
      "title": "Interview Index",
      "href": "reference/interview-index.html"
    },
    {
      "title": "Self Test",
      "href": "reference/self-test.html"
    }
  ]
};
