/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "llm-inference",
  "title": "LLM Inference Optimization",
  "sections": [
    {
      "n": "00",
      "title": "Inference Foundations",
      "lessons": [
        {
          "title": "Inference 101: Prefill, Decode, and the Metrics That Matter",
          "href": "lessons/0000-inference-101.html"
        },
        {
          "title": "Local Testing: Ollama, LM Studio, LiteLLM",
          "href": "lessons/0001-local-testing-ollama-lmstudio-litellm.html"
        }
      ]
    },
    {
      "n": "01",
      "title": "High-Throughput Serving Engines",
      "lessons": [
        {
          "title": "vLLM and PagedAttention Serving",
          "href": "lessons/0002-vllm-paged-attention-serving.html"
        },
        {
          "title": "SGLang and RadixAttention",
          "href": "lessons/0003-sglang-radixattention.html"
        },
        {
          "title": "Continuous Batching and Queue Management",
          "href": "lessons/0004-continuous-batching-queueing.html"
        },
        {
          "title": "KV Cache Eviction for Long Contexts",
          "href": "lessons/0005-kv-cache-eviction-long-context.html"
        },
        {
          "title": "Speculative Decoding and Draft Handoffs",
          "href": "lessons/0006-speculative-decoding-draft-handoff.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Quantization",
      "lessons": [
        {
          "title": "Quantization Tradeoffs: INT4, FP8, AWQ, GPTQ",
          "href": "lessons/0007-quantization-int4-fp8-awq-gptq.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Routing and Budgeting",
      "lessons": [
        {
          "title": "Build a Model Router by Cost, Latency, Quality",
          "href": "lessons/0008-model-router-cost-latency-quality.html"
        },
        {
          "title": "A Token Budgeting System per Request",
          "href": "lessons/0009-token-budgeting-per-request.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Edge and Deployment Targets",
      "lessons": [
        {
          "title": "Edge Deployment: ONNX, TensorRT, WebLLM",
          "href": "lessons/0010-edge-onnx-tensorrt-webllm.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Scale and Operations",
      "lessons": [
        {
          "title": "Kubernetes for AI Workloads",
          "href": "lessons/0011-kubernetes-for-ai-workloads.html"
        },
        {
          "title": "Observability: Latency, Tokens, Errors, Costs",
          "href": "lessons/0012-observability-latency-tokens-cost.html"
        },
        {
          "title": "Load Testing 1000+ Concurrent Requests",
          "href": "lessons/0013-load-testing-1000-concurrent.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Economics and Craft",
      "lessons": [
        {
          "title": "How Inference Costs Break Unit Economics",
          "href": "lessons/0014-inference-unit-economics.html"
        },
        {
          "title": "Capstone: Build, Benchmark, Share",
          "href": "lessons/0015-capstone-benchmark-publicly.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
