/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "gcp",
  "title": "Inside Google Cloud",
  "sections": [
    {
      "n": "01",
      "title": "The lay of the land",
      "lessons": [
        {
          "title": "Regions, zones and the scope of a resource",
          "href": "lessons/0100-regions-zones-and-scope.html"
        },
        {
          "title": "The resource hierarchy and the project",
          "href": "lessons/0101-the-resource-hierarchy.html"
        },
        {
          "title": "What flows down the tree",
          "href": "lessons/0102-what-flows-down-the-tree.html"
        },
        {
          "title": "The platform map and the names that moved",
          "href": "lessons/0103-the-platform-map.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Compute",
      "lessons": [
        {
          "title": "The machine you shape yourself",
          "href": "lessons/0200-compute-engine-the-machine-you-shape.html"
        },
        {
          "title": "Images, families and templates",
          "href": "lessons/0201-images-and-templates.html"
        },
        {
          "title": "Five levers on the same machine",
          "href": "lessons/0202-changing-what-you-rent.html"
        },
        {
          "title": "Managed instance groups and Batch",
          "href": "lessons/0203-managed-instance-groups.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Containers and serverless",
      "lessons": [
        {
          "title": "How much of the GKE cluster you run",
          "href": "lessons/0300-gke-how-much-of-the-cluster-you-run.html"
        },
        {
          "title": "Beyond one cluster",
          "href": "lessons/0301-beyond-one-cluster.html"
        },
        {
          "title": "Cloud Run, a container with a URL",
          "href": "lessons/0302-cloud-run-a-container-with-a-url.html"
        },
        {
          "title": "Functions and app runtimes",
          "href": "lessons/0303-functions-and-app-runtimes.html"
        },
        {
          "title": "Choosing a runtime",
          "href": "lessons/0304-choosing-a-runtime.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Storage",
      "lessons": [
        {
          "title": "Cloud Storage and the bucket",
          "href": "lessons/0400-cloud-storage-the-bucket.html"
        },
        {
          "title": "Classes, lifecycle and archive",
          "href": "lessons/0401-classes-lifecycle-and-archive.html"
        },
        {
          "title": "Block storage on Compute Engine",
          "href": "lessons/0402-block-storage.html"
        },
        {
          "title": "Shared filesystems",
          "href": "lessons/0403-shared-filesystems.html"
        },
        {
          "title": "Where the storage menu stops",
          "href": "lessons/0404-where-the-storage-menu-stops.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Databases",
      "lessons": [
        {
          "title": "The managed relational tier",
          "href": "lessons/0500-managed-relational.html"
        },
        {
          "title": "Spanner, and the rows it quietly fills",
          "href": "lessons/0501-spanner.html"
        },
        {
          "title": "Bigtable and Firestore",
          "href": "lessons/0502-bigtable-and-firestore.html"
        },
        {
          "title": "Memorystore and the cache tier",
          "href": "lessons/0503-memorystore.html"
        },
        {
          "title": "Moving a database in",
          "href": "lessons/0504-moving-a-database-in.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Analytics",
      "lessons": [
        {
          "title": "BigQuery, the warehouse and the query engine",
          "href": "lessons/0600-bigquery.html"
        },
        {
          "title": "BigLake and the lakehouse",
          "href": "lessons/0601-biglake-and-the-lakehouse.html"
        },
        {
          "title": "Dataflow and the streaming row",
          "href": "lessons/0602-dataflow-and-streaming.html"
        },
        {
          "title": "A recurring Spark job is two decisions",
          "href": "lessons/0603-spark-and-the-orchestrator.html"
        },
        {
          "title": "Governing and reading the data",
          "href": "lessons/0604-governing-and-reading-the-data.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Networking and delivery",
      "lessons": [
        {
          "title": "Subnets and the address plan",
          "href": "lessons/0700-subnets-and-addresses.html"
        },
        {
          "title": "Routing, egress and the firewall",
          "href": "lessons/0701-routing-egress-and-the-firewall.html"
        },
        {
          "title": "Three private paths to a managed service",
          "href": "lessons/0702-three-private-paths.html"
        },
        {
          "title": "Joining networks",
          "href": "lessons/0703-joining-networks.html"
        },
        {
          "title": "Reaching the ground",
          "href": "lessons/0704-reaching-the-ground.html"
        },
        {
          "title": "The edge, and one anycast front door",
          "href": "lessons/0705-the-edge.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Identity and access",
      "lessons": [
        {
          "title": "The IAM evaluation chain",
          "href": "lessons/0800-the-evaluation-chain.html"
        },
        {
          "title": "Boundaries and privileged access",
          "href": "lessons/0801-boundaries-and-privileged-access.html"
        },
        {
          "title": "Machine identity without keys",
          "href": "lessons/0802-machine-identity.html"
        },
        {
          "title": "Two kinds of human, two directories",
          "href": "lessons/0803-two-kinds-of-human.html"
        },
        {
          "title": "Keys, secrets and certificates",
          "href": "lessons/0804-keys-and-secrets.html"
        }
      ]
    },
    {
      "n": "09",
      "title": "Governance, tenancy and cost",
      "lessons": [
        {
          "title": "The landing zone",
          "href": "lessons/0900-the-landing-zone.html"
        },
        {
          "title": "Labels, tags and quotas",
          "href": "lessons/0901-labels-tags-and-quotas.html"
        },
        {
          "title": "Seeing and proving the estate",
          "href": "lessons/0902-seeing-the-estate.html"
        },
        {
          "title": "The bill, and where its detail lives",
          "href": "lessons/0903-the-bill.html"
        },
        {
          "title": "Paying less on purpose",
          "href": "lessons/0904-paying-less-on-purpose.html"
        }
      ]
    },
    {
      "n": "10",
      "title": "Observability and audit",
      "lessons": [
        {
          "title": "Where a log lands and how long it stays",
          "href": "lessons/1000-where-a-log-lands.html"
        },
        {
          "title": "The four audit streams",
          "href": "lessons/1001-the-four-audit-streams.html"
        },
        {
          "title": "The streams that are off until you turn them on",
          "href": "lessons/1002-streams-that-are-off.html"
        },
        {
          "title": "Metrics, agents and three retention schedules",
          "href": "lessons/1003-metrics-and-retention.html"
        },
        {
          "title": "Traces, profiles and being told",
          "href": "lessons/1004-being-told.html"
        }
      ]
    }
  ],
  "extras": []
};
