/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "herdr",
  "title": "Herdr from Zero",
  "sections": [
    {
      "n": "01",
      "title": "Herdr in one picture",
      "lessons": [
        {
          "title": "What is Herdr",
          "href": "lessons/0001-what-is-herdr.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "How it works",
      "lessons": [
        {
          "title": "The always-on server",
          "href": "lessons/0002-the-always-on-server.html"
        },
        {
          "title": "Sessions, workspaces, panes",
          "href": "lessons/0003-sessions-workspaces-panes.html"
        },
        {
          "title": "Knowing which agent is stuck",
          "href": "lessons/0004-knowing-which-agent-is-stuck.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Getting it running",
      "lessons": [
        {
          "title": "Install and first run",
          "href": "lessons/0005-install-and-first-run.html"
        },
        {
          "title": "Configuring Herdr",
          "href": "lessons/0006-configuring-herdr.html"
        },
        {
          "title": "Remote, updates and deployment",
          "href": "lessons/0007-remote-updates-and-deployment.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "What it is for",
      "lessons": [
        {
          "title": "What people use it for",
          "href": "lessons/0008-what-people-use-it-for.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Plugin development",
      "lessons": [
        {
          "title": "What a plugin is",
          "href": "lessons/0009-what-a-plugin-is.html"
        },
        {
          "title": "The plugin contract",
          "href": "lessons/0010-the-plugin-contract.html"
        },
        {
          "title": "Build your first plugin",
          "href": "lessons/0011-build-your-first-plugin.html"
        },
        {
          "title": "Plugin lifecycle and API",
          "href": "lessons/0012-plugin-lifecycle-and-api.html"
        },
        {
          "title": "Testing and publishing",
          "href": "lessons/0013-testing-and-publishing.html"
        }
      ]
    }
  ],
  "extras": []
};
