/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "aws",
  "title": "Inside AWS",
  "sections": [
    {
      "n": "01",
      "title": "The lay of the land",
      "lessons": [
        {
          "title": "Regions, zones and the edge",
          "href": "lessons/0100-regions-zones-and-the-edge.html"
        },
        {
          "title": "The account is the boundary",
          "href": "lessons/0101-the-account-is-the-boundary.html"
        },
        {
          "title": "The platform map",
          "href": "lessons/0102-the-platform-map.html"
        },
        {
          "title": "Names that mislead",
          "href": "lessons/0103-names-that-mislead.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Compute",
      "lessons": [
        {
          "title": "The instance and the catalogue",
          "href": "lessons/0200-the-instance-and-the-catalogue.html"
        },
        {
          "title": "The image and the template",
          "href": "lessons/0201-the-image-and-the-template.html"
        },
        {
          "title": "Where the instance lands",
          "href": "lessons/0202-where-the-instance-lands.html"
        },
        {
          "title": "Holding a fleet at a size",
          "href": "lessons/0203-holding-a-fleet-at-a-size.html"
        },
        {
          "title": "Buying the same machine for less",
          "href": "lessons/0204-buying-the-same-machine-for-less.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Containers and serverless",
      "lessons": [
        {
          "title": "Two orchestrators, one platform",
          "href": "lessons/0300-two-orchestrators-one-platform.html"
        },
        {
          "title": "Fargate is a capacity mode",
          "href": "lessons/0301-fargate-is-a-capacity-mode.html"
        },
        {
          "title": "The registry that feeds them",
          "href": "lessons/0302-the-registry-that-feeds-them.html"
        },
        {
          "title": "Lambda and the function boundary",
          "href": "lessons/0303-lambda-and-the-function-boundary.html"
        },
        {
          "title": "Above the container",
          "href": "lessons/0304-above-the-container.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Storage",
      "lessons": [
        {
          "title": "The object store and its classes",
          "href": "lessons/0400-the-object-store-and-its-classes.html"
        },
        {
          "title": "The bucket types",
          "href": "lessons/0401-the-bucket-types.html"
        },
        {
          "title": "Block storage, bound to a zone",
          "href": "lessons/0402-block-storage-bound-to-a-zone.html"
        },
        {
          "title": "Shared file systems",
          "href": "lessons/0403-shared-file-systems.html"
        },
        {
          "title": "Cold data and getting data in",
          "href": "lessons/0404-cold-data-and-getting-data-in.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Databases",
      "lessons": [
        {
          "title": "Two storage designs under one API",
          "href": "lessons/0500-two-storage-designs-under-one-api.html"
        },
        {
          "title": "Capacity with no instance class",
          "href": "lessons/0501-capacity-with-no-instance-class.html"
        },
        {
          "title": "DynamoDB and the partition",
          "href": "lessons/0502-dynamodb-and-the-partition.html"
        },
        {
          "title": "Two in-memory services",
          "href": "lessons/0503-two-in-memory-services.html"
        },
        {
          "title": "The purpose-built stores",
          "href": "lessons/0504-the-purpose-built-stores.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Analytics",
      "lessons": [
        {
          "title": "The lake is three layers",
          "href": "lessons/0600-the-lake-is-three-layers.html"
        },
        {
          "title": "Three ways to read the lake",
          "href": "lessons/0601-three-ways-to-read-the-lake.html"
        },
        {
          "title": "The warehouse beside the lake",
          "href": "lessons/0602-the-warehouse-beside-the-lake.html"
        },
        {
          "title": "Two ways to run a Spark job",
          "href": "lessons/0603-two-ways-to-run-a-spark-job.html"
        },
        {
          "title": "Ingest, deliver, process",
          "href": "lessons/0604-ingest-deliver-process.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Networking and delivery",
      "lessons": [
        {
          "title": "The interface, the address and the route",
          "href": "lessons/0700-the-interface-the-address-and-the-route.html"
        },
        {
          "title": "Two filters that both must pass",
          "href": "lessons/0701-two-filters-that-both-must-pass.html"
        },
        {
          "title": "Egress and private access",
          "href": "lessons/0702-egress-and-private-access.html"
        },
        {
          "title": "From peering to a hub",
          "href": "lessons/0703-from-peering-to-a-hub.html"
        },
        {
          "title": "The front door",
          "href": "lessons/0704-the-front-door.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Identity and access",
      "lessons": [
        {
          "title": "The gates an access decision passes",
          "href": "lessons/0800-the-gates-an-access-decision-passes.html"
        },
        {
          "title": "Machines carry no passwords",
          "href": "lessons/0801-machines-carry-no-passwords.html"
        },
        {
          "title": "Trusting an identity from outside",
          "href": "lessons/0802-trusting-an-identity-from-outside.html"
        },
        {
          "title": "Neither your staff nor your customers",
          "href": "lessons/0803-neither-your-staff-nor-your-customers.html"
        },
        {
          "title": "Keys, secrets and certificates",
          "href": "lessons/0804-keys-secrets-and-certificates.html"
        }
      ]
    },
    {
      "n": "09",
      "title": "Governance, tenancy and cost",
      "lessons": [
        {
          "title": "Shaping the tree",
          "href": "lessons/0900-shaping-the-tree.html"
        },
        {
          "title": "Two ceilings that grant nothing",
          "href": "lessons/0901-two-ceilings-that-grant-nothing.html"
        },
        {
          "title": "The landing zone and the catalogue",
          "href": "lessons/0902-the-landing-zone-and-the-catalogue.html"
        },
        {
          "title": "Quotas, tags and what you own",
          "href": "lessons/0903-quotas-tags-and-what-you-own.html"
        },
        {
          "title": "The cost model",
          "href": "lessons/0904-the-cost-model.html"
        }
      ]
    },
    {
      "n": "10",
      "title": "Observability and audit",
      "lessons": [
        {
          "title": "Three stores and no workspace",
          "href": "lessons/1000-three-stores-and-no-workspace.html"
        },
        {
          "title": "What is on and what is off",
          "href": "lessons/1001-what-is-on-and-what-is-off.html"
        },
        {
          "title": "How fast each stream arrives",
          "href": "lessons/1002-how-fast-each-stream-arrives.html"
        },
        {
          "title": "Noticing and acting",
          "href": "lessons/1003-noticing-and-acting.html"
        },
        {
          "title": "Instrumenting, and what telemetry cannot answer",
          "href": "lessons/1004-instrumenting-and-what-telemetry-cannot-answer.html"
        }
      ]
    },
    {
      "n": "11",
      "title": "Security services",
      "lessons": [
        {
          "title": "Protection at the edge",
          "href": "lessons/1100-protection-at-the-edge.html"
        },
        {
          "title": "Inspection inside the network",
          "href": "lessons/1101-inspection-inside-the-network.html"
        },
        {
          "title": "Four detectors",
          "href": "lessons/1102-four-detectors.html"
        },
        {
          "title": "Posture and org-wide enforcement",
          "href": "lessons/1103-posture-and-org-wide-enforcement.html"
        },
        {
          "title": "Three decisions above the network",
          "href": "lessons/1104-three-decisions-above-the-network.html"
        }
      ]
    },
    {
      "n": "12",
      "title": "Delivery and integration",
      "lessons": [
        {
          "title": "Describing infrastructure",
          "href": "lessons/1200-describing-infrastructure.html"
        },
        {
          "title": "The pipeline",
          "href": "lessons/1201-the-pipeline.html"
        },
        {
          "title": "Shipping change gradually",
          "href": "lessons/1202-shipping-change-gradually.html"
        },
        {
          "title": "Queues, topics and buses",
          "href": "lessons/1203-queues-topics-and-buses.html"
        },
        {
          "title": "Workflows and API surfaces",
          "href": "lessons/1204-workflows-and-api-surfaces.html"
        }
      ]
    }
  ],
  "extras": []
};
