/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "agent-engineering",
  "title": "Production Agent Engineering",
  "sections": [
    {
      "n": "01",
      "title": "Substrate",
      "lessons": [
        {
          "title": "Context and Protocol",
          "href": "lessons/0000-context-and-protocol.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Measurement",
      "lessons": [
        {
          "title": "Evaluation and the Data Flywheel",
          "href": "lessons/0001-evaluation-and-the-data-flywheel.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Durability",
      "lessons": [
        {
          "title": "State, Async and Degradation",
          "href": "lessons/0002-state-async-and-degradation.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Economics",
      "lessons": [
        {
          "title": "Latency, Cost and Local-First",
          "href": "lessons/0003-latency-cost-and-local-first.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Isolation",
      "lessons": [
        {
          "title": "Retrieval and Isolation",
          "href": "lessons/0004-retrieval-and-isolation.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
