/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "coding-harness",
  "title": "Coding Harness Engineering",
  "sections": [
    {
      "n": "01",
      "title": "Orientation",
      "lessons": [
        {
          "title": "What a coding harness is - the seven layers",
          "href": "lessons/0000-what-is-a-coding-harness.html"
        },
        {
          "title": "Eleven principles behind every harness",
          "href": "lessons/0010-agentic-system-design.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "The Loop",
      "lessons": [
        {
          "title": "The turn cycle - the loop every harness runs",
          "href": "lessons/0020-the-turn-cycle.html"
        },
        {
          "title": "Context engineering - what actually fills the window",
          "href": "lessons/0030-context-engineering.html"
        },
        {
          "title": "The edit problem - applying a change that does not apply",
          "href": "lessons/0040-edit-problem.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Trust",
      "lessons": [
        {
          "title": "Permission postures - ask, sandbox, classify, or nothing",
          "href": "lessons/0050-permission-postures.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Extending",
      "lessons": [
        {
          "title": "Skills, subagents, hooks and modes",
          "href": "lessons/0080-customization-primitives.html"
        },
        {
          "title": "Code mode - tool calls as generated programs",
          "href": "lessons/0090-code-mode.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Deep Dives - the cast of fifteen",
      "lessons": [
        {
          "title": "Aider - the repo map and the pre-agentic lineage",
          "href": "lessons/0120-aider.html"
        },
        {
          "title": "OpenAI Codex CLI - enforce first, ask second",
          "href": "lessons/0140-codex-cli.html"
        },
        {
          "title": "Cursor - the harness that trains its own models",
          "href": "lessons/0150-cursor-trains-own-models.html"
        },
        {
          "title": "GitHub Copilot Chat - prompts as a component tree",
          "href": "lessons/0160-copilot-chat.html"
        },
        {
          "title": "Gemini CLI - the self-healing edit pipeline",
          "href": "lessons/0170-gemini-cli-self-healing.html"
        },
        {
          "title": "Windsurf - the human trajectory as context",
          "href": "lessons/0180-windsurf.html"
        },
        {
          "title": "Roo Code - the mode system",
          "href": "lessons/0210-roo-code.html"
        },
        {
          "title": "Pi - the agent loop as a library",
          "href": "lessons/0240-pi.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
