/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "coding-harness",
  "title": "Coding Harness Engineering",
  "sections": [
    {
      "n": "01",
      "title": "Orientation",
      "lessons": [
        {
          "title": "What a coding harness is - the seven layers",
          "href": "lessons/0000-what-is-a-coding-harness.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Trust",
      "lessons": [
        {
          "title": "Permission postures - ask, sandbox, classify, or nothing",
          "href": "lessons/0050-permission-postures.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Deep Dives - the cast of fifteen",
      "lessons": [
        {
          "title": "OpenAI Codex CLI - enforce first, ask second",
          "href": "lessons/0140-codex-cli.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
