#!/usr/bin/env python3
"""Generate a course outline manifest from the course index page.

The course ``index.html`` stays the hand-authored source of truth. This reads
its module headings and lesson cards and writes ``<course>/outline.js``, the
data file the shared rail renders from. Run it after adding a lesson and commit
the result; the site itself never runs this, so the zero-build shape is intact.

    python3 scripts/gen_outline.py llm-papers-course
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parent.parent

MODULE_PATTERN = re.compile(
    r'<div class="module-h">\s*<span class="mnum">(?P<num>.*?)</span>\s*<h3>(?P<title>.*?)</h3>',
    re.DOTALL,
)
# Courses register a lesson either as a full card or as a line in a parts list,
# so match any anchor pointing into lessons/ and take the best title it offers.
LESSON_PATTERN = re.compile(
    r'<a\b[^>]*href="(?P<href>lessons/[^"#?]+)"[^>]*>(?P<body>.*?)</a>',
    re.DOTALL,
)
CARD_TITLE_PATTERN = re.compile(r'<div class="lt">(?P<title>.*?)</div>', re.DOTALL)
EXTRA_PATTERN = re.compile(r'href="(?P<href>reference/[^"#?]+)"')


def clean(raw: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", raw)).strip()


def parse(index_html: str) -> tuple[list[dict[str, object]], list[dict[str, str]]]:
    """Split the page at each module heading, then collect that module's cards."""
    boundaries = [(match.start(), match) for match in MODULE_PATTERN.finditer(index_html)]
    sections: list[dict[str, object]] = []

    for position, (start, match) in enumerate(boundaries):
        end = boundaries[position + 1][0] if position + 1 < len(boundaries) else len(index_html)
        lessons: list[dict[str, str]] = []
        claimed: set[str] = set()
        for anchor in LESSON_PATTERN.finditer(index_html[start:end]):
            href = anchor.group("href")
            if href in claimed:
                continue
            claimed.add(href)
            card_title = CARD_TITLE_PATTERN.search(anchor.group("body"))
            title = clean(card_title.group("title")) if card_title else clean(anchor.group("body"))
            lessons.append({"title": title, "href": href})
        if lessons:
            sections.append(
                {"n": clean(match.group("num")), "title": clean(match.group("title")), "lessons": lessons}
            )

    seen: set[str] = set()
    extras: list[dict[str, str]] = []
    for match in EXTRA_PATTERN.finditer(index_html):
        href = match.group("href")
        if href in seen:
            continue
        seen.add(href)
        extras.append({"title": Path(href).stem.replace("-", " ").title(), "href": href})
    return sections, extras


def title_of(index_html: str) -> str:
    match = re.search(r"<title>(.*?)</title>", index_html, re.DOTALL)
    return clean(match.group(1)).split(" - ")[0] if match else "Course"


def render(course: str, index_html: str) -> str:
    sections, extras = parse(index_html)
    payload = {
        "key": course.removesuffix("-course"),
        "title": title_of(index_html),
        "sections": sections,
        "extras": extras,
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "/* Generated by scripts/gen_outline.py from this course's index.html.\n"
        "   The index page is the source of truth. Re-run the generator after\n"
        "   adding a lesson; validate_site.py fails the pull request if this\n"
        "   file and the index disagree. */\n"
        f"window.COURSE_OUTLINE = {body};\n"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    course = argv[1].rstrip("/")
    index_path = REPO_ROOT / course / "index.html"
    if not index_path.is_file():
        print(f"no such course index: {index_path}")
        return 1
    out = REPO_ROOT / course / "outline.js"
    out.write_text(render(course, index_path.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
