/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "llm-efficiency",
  "title": "LLM Efficiency on Desk Hardware",
  "sections": [
    {
      "n": "01",
      "title": "The Wall",
      "lessons": [
        {
          "title": "Start Here",
          "href": "lessons/0000-start-here.html"
        },
        {
          "title": "Generation Is a Bandwidth Problem",
          "href": "lessons/0001-generation-is-a-bandwidth-problem.html"
        },
        {
          "title": "A 320B MoE Reads Like an 18B Model",
          "href": "lessons/0002-moe-total-versus-active-parameters.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Shrinking the Model",
      "lessons": [
        {
          "title": "Quantization Spends Rounding Error to Shrink Memory",
          "href": "lessons/0003-quantization-shrinks-weights-by-spending-error.html"
        },
        {
          "title": "The Format Decides Where the Model Runs",
          "href": "lessons/0004-pick-the-format-gguf-fp8-nvfp4.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Steering a Frozen Model",
      "lessons": [
        {
          "title": "LoRA Steers a Frozen Model with Two Small Matrices",
          "href": "lessons/0005-lora-steers-a-frozen-model-with-two-small-matrices.html"
        },
        {
          "title": "QLoRA Fine-Tunes a Model That Does Not Fit Unfrozen",
          "href": "lessons/0006-qlora-fine-tunes-in-4-bit.html"
        },
        {
          "title": "LoRA Is One Point in a Family of Cheap Adapters",
          "href": "lessons/0007-the-wider-peft-family.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Making It Fast, Then Deploying It",
      "lessons": [
        {
          "title": "Speculative Decoding Trades Spare Compute for Bandwidth",
          "href": "lessons/0008-speculative-decoding-buys-bandwidth-with-compute.html"
        },
        {
          "title": "Two DGX Sparks Run a 320B MoE at NVFP4",
          "href": "lessons/0009-case-study-glm-on-two-dgx-sparks.html"
        },
        {
          "title": "One 256 GB Mac Runs the Same Model Alone",
          "href": "lessons/0010-case-study-mac-studio-256gb.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
