/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "backend-engineering",
  "title": "Backend Engineering",
  "sections": [
    {
      "n": "01",
      "title": "The shape of a request",
      "lessons": [
        {
          "title": "The shape of a request",
          "href": "lessons/0000-the-shape-of-a-request.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "HTTP is the language",
      "lessons": [
        {
          "title": "A request is a method, a target and headers",
          "href": "lessons/0200-a-request-is-a-method-a-target-and-headers.html"
        },
        {
          "title": "Methods are verbs with guarantees",
          "href": "lessons/0201-methods-are-verbs-with-guarantees.html"
        },
        {
          "title": "Status codes are three families with one job each",
          "href": "lessons/0202-status-codes-are-three-families-with-one-job-each.html"
        },
        {
          "title": "Headers carry what the body cannot",
          "href": "lessons/0203-headers-carry-what-the-body-cannot.html"
        },
        {
          "title": "Caching is a contract between two clocks",
          "href": "lessons/0204-caching-is-a-contract-between-two-clocks.html"
        },
        {
          "title": "CORS is the browser enforcing the server's own policy",
          "href": "lessons/0205-cors-is-the-browser-enforcing-the-servers-own-policy.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Serialization and contracts",
      "lessons": [
        {
          "title": "A wire format is a contract you can break silently",
          "href": "lessons/0400-a-wire-format-is-a-contract-you-can-break-silently.html"
        },
        {
          "title": "JSON is text and text has no types",
          "href": "lessons/0401-json-is-text-and-text-has-no-types.html"
        },
        {
          "title": "Schema-first makes the contract the source",
          "href": "lessons/0402-schema-first-makes-the-contract-the-source.html"
        },
        {
          "title": "Validation belongs at the boundary, once",
          "href": "lessons/0403-validation-belongs-at-the-boundary-once.html"
        },
        {
          "title": "Content negotiation picks the representation",
          "href": "lessons/0404-content-negotiation-picks-the-representation.html"
        },
        {
          "title": "Compatibility is a rule, not a hope",
          "href": "lessons/0405-compatibility-is-a-rule-not-a-hope.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "API design",
      "lessons": [
        {
          "title": "An API is a promise with a cost of breaking",
          "href": "lessons/0600-an-api-is-a-promise-with-a-cost-of-breaking.html"
        },
        {
          "title": "Resources are nouns and the method is the verb",
          "href": "lessons/0601-resources-are-nouns-and-the-method-is-the-verb.html"
        },
        {
          "title": "Collections need pagination, not a limit",
          "href": "lessons/0602-collections-need-pagination-not-a-limit.html"
        },
        {
          "title": "An error body is part of the contract",
          "href": "lessons/0603-an-error-body-is-part-of-the-contract.html"
        },
        {
          "title": "Versioning is choosing who pays to change",
          "href": "lessons/0604-versioning-is-choosing-who-pays-to-change.html"
        },
        {
          "title": "Idempotency keys make retries safe",
          "href": "lessons/0605-idempotency-keys-make-retries-safe.html"
        }
      ]
    },
    {
      "n": "13",
      "title": "Scale, fleet and shipping",
      "lessons": [
        {
          "title": "Concurrency is how a server waits",
          "href": "lessons/1300-concurrency-is-how-a-server-waits.html"
        },
        {
          "title": "Shared state is where concurrency is paid for",
          "href": "lessons/1301-shared-state-is-where-concurrency-is-paid-for.html"
        },
        {
          "title": "Statelessness is what makes a fleet possible",
          "href": "lessons/1302-statelessness-is-what-makes-a-fleet-possible.html"
        },
        {
          "title": "A container is a process with its own view",
          "href": "lessons/1303-a-container-is-a-process-with-its-own-view.html"
        },
        {
          "title": "Kubernetes is a control loop, not a deployer",
          "href": "lessons/1304-kubernetes-is-a-control-loop-not-a-deployer.html"
        },
        {
          "title": "Tests buy confidence at different prices",
          "href": "lessons/1305-tests-buy-confidence-at-different-prices.html"
        },
        {
          "title": "The pipeline ships the artefact you tested",
          "href": "lessons/1306-the-pipeline-ships-the-artefact-you-tested.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
