/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "backend-engineering",
  "title": "Backend Engineering",
  "sections": [
    {
      "n": "01",
      "title": "The shape of a request",
      "lessons": [
        {
          "title": "The shape of a request",
          "href": "lessons/0000-the-shape-of-a-request.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
