/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "production-systems",
  "title": "Production Systems: 111 Topics at Three Scales",
  "sections": [
    {
      "n": "01",
      "title": "The Request Path",
      "lessons": [
        {
          "title": "Edge and Traffic Management",
          "href": "lessons/0000-edge-and-traffic.html"
        },
        {
          "title": "Resilience Patterns",
          "href": "lessons/0001-resilience-patterns.html"
        },
        {
          "title": "Asynchronous and Event-Driven",
          "href": "lessons/0002-async-and-event-driven.html"
        },
        {
          "title": "Protocols and Real-Time Transport",
          "href": "lessons/0003-protocols-and-real-time.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "State",
      "lessons": [
        {
          "title": "Database Performance",
          "href": "lessons/0004-database-performance.html"
        },
        {
          "title": "Distributing Data",
          "href": "lessons/0005-distributed-data.html"
        },
        {
          "title": "Concurrency and Runtime",
          "href": "lessons/0006-concurrency-and-runtime.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Running It",
      "lessons": [
        {
          "title": "Scale, Latency and Cost",
          "href": "lessons/0007-scale-latency-and-cost.html"
        },
        {
          "title": "Delivery and Deployment",
          "href": "lessons/0008-delivery-and-deployment.html"
        },
        {
          "title": "Observability and Operations",
          "href": "lessons/0009-observability-and-operations.html"
        },
        {
          "title": "Security",
          "href": "lessons/0010-security.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
