/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "ai-software-developer",
  "title": "AI Software Developer",
  "sections": [
    {
      "n": "00",
      "title": "Start here",
      "lessons": [
        {
          "title": "You are already running one",
          "href": "lessons/0000-you-are-already-running-one.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Agent-ready codebases",
      "lessons": [
        {
          "title": "What agent-ready means",
          "href": "lessons/0500-what-agent-ready-means.html"
        },
        {
          "title": "The nine pillars and five levels",
          "href": "lessons/0510-the-nine-pillars-and-five-levels.html"
        },
        {
          "title": "Tests are the agent's feedback loop",
          "href": "lessons/0520-tests-are-the-agents-feedback-loop.html"
        },
        {
          "title": "Reproducible environments",
          "href": "lessons/0530-reproducible-environments.html"
        },
        {
          "title": "CI an agent can read",
          "href": "lessons/0540-ci-an-agent-can-read.html"
        },
        {
          "title": "Scoring a repository",
          "href": "lessons/0550-scoring-a-repository.html"
        },
        {
          "title": "The gaps that block agents",
          "href": "lessons/0560-the-gaps-that-block-agents.html"
        },
        {
          "title": "In the field: Factory",
          "href": "lessons/0570-in-the-field-factory.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Security",
      "lessons": [
        {
          "title": "The three scanners",
          "href": "lessons/0700-the-three-scanners.html"
        },
        {
          "title": "Writing a rule",
          "href": "lessons/0710-writing-a-rule.html"
        },
        {
          "title": "The agent attack surface",
          "href": "lessons/0720-the-agent-attack-surface.html"
        },
        {
          "title": "Permissions are the defence",
          "href": "lessons/0730-permissions-are-the-defence.html"
        },
        {
          "title": "Sandboxes and hooks",
          "href": "lessons/0740-sandboxes-and-hooks.html"
        },
        {
          "title": "Scanners in CI",
          "href": "lessons/0750-scanners-in-ci.html"
        },
        {
          "title": "Triage and auto-fix",
          "href": "lessons/0760-triage-and-auto-fix.html"
        },
        {
          "title": "In the field: Semgrep",
          "href": "lessons/0770-in-the-field-semgrep.html"
        }
      ]
    },
    {
      "n": "09",
      "title": "Building an AI-native team",
      "lessons": [
        {
          "title": "One door for every tool",
          "href": "lessons/0900-one-door-for-every-tool.html"
        },
        {
          "title": "Who is this token for?",
          "href": "lessons/0910-mcp-authorization-in-practice.html"
        },
        {
          "title": "Granting and taking away",
          "href": "lessons/0920-granting-and-auditing-tool-access.html"
        },
        {
          "title": "One place the model bill is paid",
          "href": "lessons/0930-the-llm-gateway.html"
        },
        {
          "title": "What a token actually costs",
          "href": "lessons/0940-what-a-token-actually-costs.html"
        },
        {
          "title": "Making the good setup the default one",
          "href": "lessons/0950-rolling-it-out-to-a-team.html"
        },
        {
          "title": "Measuring adoption honestly",
          "href": "lessons/0960-measuring-adoption-honestly.html"
        },
        {
          "title": "In the field: Replit",
          "href": "lessons/0970-in-the-field-replit.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
