/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "ai-software-developer",
  "title": "AI Software Developer",
  "sections": [
    {
      "n": "00",
      "title": "Start here",
      "lessons": [
        {
          "title": "You are already running one",
          "href": "lessons/0000-you-are-already-running-one.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
