/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "ai-software-developer",
  "title": "AI Software Developer",
  "sections": [
    {
      "n": "00",
      "title": "Start here",
      "lessons": [
        {
          "title": "You are already running one",
          "href": "lessons/0000-you-are-already-running-one.html"
        }
      ]
    },
    {
      "n": "01",
      "title": "The internals of coding agents",
      "lessons": [
        {
          "title": "What the model actually receives",
          "href": "lessons/0100-what-the-model-actually-receives.html"
        },
        {
          "title": "The loop in one picture",
          "href": "lessons/0110-the-loop-in-one-picture.html"
        },
        {
          "title": "The core four tools",
          "href": "lessons/0120-the-core-four-tools.html"
        },
        {
          "title": "Reading a tool-call trace",
          "href": "lessons/0130-reading-a-tool-call-trace.html"
        },
        {
          "title": "How a system prompt is assembled",
          "href": "lessons/0140-how-a-system-prompt-is-assembled.html"
        },
        {
          "title": "A tool definition is a contract",
          "href": "lessons/0150-a-tool-definition-is-a-contract.html"
        },
        {
          "title": "Two hundred lines",
          "href": "lessons/0160-two-hundred-lines.html"
        },
        {
          "title": "What a shipped harness does that yours does not",
          "href": "lessons/0170-what-your-agent-does-that-yours-does-not.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Advanced context engineering",
      "lessons": [
        {
          "title": "The window is a budget",
          "href": "lessons/0200-the-window-is-a-budget.html"
        },
        {
          "title": "Which prompting technique, when",
          "href": "lessons/0210-which-prompting-technique-when.html"
        },
        {
          "title": "RePPIT, the five moves",
          "href": "lessons/0220-reppit-the-five-moves.html"
        },
        {
          "title": "Spec-driven development",
          "href": "lessons/0230-spec-driven-development.html"
        },
        {
          "title": "MCP in one page",
          "href": "lessons/0240-mcp-in-one-page.html"
        },
        {
          "title": "Write your first MCP server",
          "href": "lessons/0250-write-your-first-mcp-server.html"
        },
        {
          "title": "Tools are designed for a reader who cannot ask",
          "href": "lessons/0260-tools-are-designed-for-a-reader-who-cannot-ask.html"
        },
        {
          "title": "When not to add a tool",
          "href": "lessons/0270-when-not-to-add-a-tool.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Agent skills and the CLI",
      "lessons": [
        {
          "title": "What a skill is",
          "href": "lessons/0300-what-a-skill-is.html"
        },
        {
          "title": "Writing your first skill",
          "href": "lessons/0310-writing-your-first-skill.html"
        },
        {
          "title": "Progressive disclosure, and scripts",
          "href": "lessons/0320-progressive-disclosure-and-scripts.html"
        },
        {
          "title": "Where skills live",
          "href": "lessons/0330-where-skills-live.html"
        },
        {
          "title": "Web skills",
          "href": "lessons/0340-web-skills.html"
        },
        {
          "title": "The agent in a pipeline",
          "href": "lessons/0350-the-agent-in-a-pipeline.html"
        },
        {
          "title": "Session control from the CLI",
          "href": "lessons/0360-session-control-from-the-cli.html"
        },
        {
          "title": "In the field: Cursor",
          "href": "lessons/0370-in-the-field-cursor.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Customizing your agent and repository",
      "lessons": [
        {
          "title": "One file, two readers",
          "href": "lessons/0400-one-file-two-readers.html"
        },
        {
          "title": "What belongs in the file",
          "href": "lessons/0410-what-belongs-in-the-file.html"
        },
        {
          "title": "The loading hierarchy",
          "href": "lessons/0420-the-loading-hierarchy.html"
        },
        {
          "title": "Hooks are the enforcement layer",
          "href": "lessons/0430-hooks-are-the-enforcement-layer.html"
        },
        {
          "title": "Writing a blocking hook",
          "href": "lessons/0440-writing-a-blocking-hook.html"
        },
        {
          "title": "The Stop hook closes the loop",
          "href": "lessons/0450-the-stop-hook-closes-the-loop.html"
        },
        {
          "title": "Planner, implementer, reviewer",
          "href": "lessons/0460-planner-implementer-reviewer.html"
        },
        {
          "title": "In the field: Claude Code",
          "href": "lessons/0470-in-the-field-claude-code.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Agent-ready codebases",
      "lessons": [
        {
          "title": "What agent-ready means",
          "href": "lessons/0500-what-agent-ready-means.html"
        },
        {
          "title": "The nine pillars and five levels",
          "href": "lessons/0510-the-nine-pillars-and-five-levels.html"
        },
        {
          "title": "Tests are the agent's feedback loop",
          "href": "lessons/0520-tests-are-the-agents-feedback-loop.html"
        },
        {
          "title": "Reproducible environments",
          "href": "lessons/0530-reproducible-environments.html"
        },
        {
          "title": "CI an agent can read",
          "href": "lessons/0540-ci-an-agent-can-read.html"
        },
        {
          "title": "Scoring a repository",
          "href": "lessons/0550-scoring-a-repository.html"
        },
        {
          "title": "The gaps that block agents",
          "href": "lessons/0560-the-gaps-that-block-agents.html"
        },
        {
          "title": "In the field: Factory",
          "href": "lessons/0570-in-the-field-factory.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Agentic code review",
      "lessons": [
        {
          "title": "What review is actually for",
          "href": "lessons/0600-what-review-is-actually-for.html"
        },
        {
          "title": "What AI review catches",
          "href": "lessons/0610-what-ai-review-catches.html"
        },
        {
          "title": "What AI review misses",
          "href": "lessons/0620-what-ai-review-misses.html"
        },
        {
          "title": "Review architectures",
          "href": "lessons/0630-review-architectures.html"
        },
        {
          "title": "Rules you write down",
          "href": "lessons/0640-rules-you-write-down.html"
        },
        {
          "title": "Wiring review into the pull request",
          "href": "lessons/0650-wiring-review-into-the-pull-request.html"
        },
        {
          "title": "Measuring your reviewer",
          "href": "lessons/0660-measuring-your-reviewer.html"
        },
        {
          "title": "In the field: Cognition",
          "href": "lessons/0670-in-the-field-cognition.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Security",
      "lessons": [
        {
          "title": "The three scanners",
          "href": "lessons/0700-the-three-scanners.html"
        },
        {
          "title": "Writing a rule",
          "href": "lessons/0710-writing-a-rule.html"
        },
        {
          "title": "The agent attack surface",
          "href": "lessons/0720-the-agent-attack-surface.html"
        },
        {
          "title": "Permissions are the defence",
          "href": "lessons/0730-permissions-are-the-defence.html"
        },
        {
          "title": "Sandboxes and hooks",
          "href": "lessons/0740-sandboxes-and-hooks.html"
        },
        {
          "title": "Scanners in CI",
          "href": "lessons/0750-scanners-in-ci.html"
        },
        {
          "title": "Triage and auto-fix",
          "href": "lessons/0760-triage-and-auto-fix.html"
        },
        {
          "title": "In the field: Semgrep",
          "href": "lessons/0770-in-the-field-semgrep.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Background agents",
      "lessons": [
        {
          "title": "What a background agent is",
          "href": "lessons/0800-what-a-background-agent-is.html"
        },
        {
          "title": "The six cloud agents",
          "href": "lessons/0810-the-six-cloud-agents.html"
        },
        {
          "title": "Triggers",
          "href": "lessons/0820-triggers.html"
        },
        {
          "title": "Issue to pull request",
          "href": "lessons/0830-issue-to-pr.html"
        },
        {
          "title": "Running a fleet",
          "href": "lessons/0840-running-a-fleet.html"
        },
        {
          "title": "What you owe a background agent",
          "href": "lessons/0850-what-you-owe-a-background-agent.html"
        },
        {
          "title": "In the field: Cloudflare",
          "href": "lessons/0860-in-the-field-cloudflare.html"
        }
      ]
    },
    {
      "n": "09",
      "title": "Building an AI-native team",
      "lessons": [
        {
          "title": "One door for every tool",
          "href": "lessons/0900-one-door-for-every-tool.html"
        },
        {
          "title": "Who is this token for?",
          "href": "lessons/0910-mcp-authorization-in-practice.html"
        },
        {
          "title": "Granting and taking away",
          "href": "lessons/0920-granting-and-auditing-tool-access.html"
        },
        {
          "title": "One place the model bill is paid",
          "href": "lessons/0930-the-llm-gateway.html"
        },
        {
          "title": "What a token actually costs",
          "href": "lessons/0940-what-a-token-actually-costs.html"
        },
        {
          "title": "Making the good setup the default one",
          "href": "lessons/0950-rolling-it-out-to-a-team.html"
        },
        {
          "title": "Measuring adoption honestly",
          "href": "lessons/0960-measuring-adoption-honestly.html"
        },
        {
          "title": "In the field: Replit",
          "href": "lessons/0970-in-the-field-replit.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
