/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "statistical-foundations-ml",
  "title": "Statistical Foundations of Machine Learning",
  "sections": [
    {
      "n": "L1",
      "title": "Lecture 1: Introduction",
      "lessons": [
        {
          "title": "Start here",
          "href": "lessons/0000-lecture-1-start-here.html"
        },
        {
          "title": "Two engines: probability and statistics",
          "href": "lessons/0001-two-engines-probability-and-statistics.html"
        },
        {
          "title": "Robust summaries: mean against median",
          "href": "lessons/0002-robust-summaries-mean-vs-median.html"
        },
        {
          "title": "Why the median survives outliers",
          "href": "lessons/0003-why-the-median-survives-outliers.html"
        },
        {
          "title": "From baseline to risk: the exponential model",
          "href": "lessons/0004-from-baseline-to-risk-the-exponential-model.html"
        },
        {
          "title": "A/B testing, the CLT, and confidence intervals",
          "href": "lessons/0005-ab-testing-the-clt-and-confidence-intervals.html"
        },
        {
          "title": "The power of n",
          "href": "lessons/0006-the-power-of-n.html"
        },
        {
          "title": "Leading indicators and correlation",
          "href": "lessons/0007-leading-indicators-and-correlation.html"
        },
        {
          "title": "Synthesis and the road ahead",
          "href": "lessons/0008-synthesis-and-the-road-ahead.html"
        }
      ]
    },
    {
      "n": "L2",
      "title": "Lecture 2: The probability space",
      "lessons": [
        {
          "title": "Start here",
          "href": "lessons/0009-lecture-2-start-here.html"
        },
        {
          "title": "The language of sets",
          "href": "lessons/0010-the-language-of-sets.html"
        },
        {
          "title": "The sample space",
          "href": "lessons/0011-the-sample-space.html"
        },
        {
          "title": "Events are subsets",
          "href": "lessons/0012-events-are-subsets.html"
        },
        {
          "title": "The sigma-field",
          "href": "lessons/0013-the-sigma-field.html"
        },
        {
          "title": "The probability measure",
          "href": "lessons/0014-the-probability-measure.html"
        },
        {
          "title": "A discrete space worked",
          "href": "lessons/0015-a-discrete-space-worked.html"
        }
      ]
    },
    {
      "n": "L3",
      "title": "Lecture 3: From the axioms to Bayes",
      "lessons": [
        {
          "title": "Start here",
          "href": "lessons/0016-lecture-3-start-here.html"
        },
        {
          "title": "What the axioms force",
          "href": "lessons/0017-what-the-axioms-force.html"
        },
        {
          "title": "Inclusion-exclusion",
          "href": "lessons/0018-inclusion-exclusion.html"
        },
        {
          "title": "The union bound and Bonferroni",
          "href": "lessons/0019-union-bound-and-bonferroni.html"
        },
        {
          "title": "Conditional probability",
          "href": "lessons/0020-conditional-probability.html"
        },
        {
          "title": "The multiplication rule",
          "href": "lessons/0021-the-multiplication-rule.html"
        },
        {
          "title": "The law of total probability",
          "href": "lessons/0022-law-of-total-probability.html"
        },
        {
          "title": "Bayes rule",
          "href": "lessons/0023-bayes-rule.html"
        },
        {
          "title": "Independence",
          "href": "lessons/0024-independence.html"
        }
      ]
    },
    {
      "n": "TA1",
      "title": "TA Session 1: twelve problems, worked in full",
      "lessons": [
        {
          "title": "TA Session 1: start here",
          "href": "lessons/0025-ta-session-1-start-here.html"
        },
        {
          "title": "Checking sigma-fields",
          "href": "lessons/0026-checking-sigma-fields.html"
        },
        {
          "title": "Is it a probability measure?",
          "href": "lessons/0027-is-it-a-probability-measure.html"
        },
        {
          "title": "Probability properties, with numbers",
          "href": "lessons/0028-probability-properties-with-numbers.html"
        },
        {
          "title": "Geometry and counting",
          "href": "lessons/0029-geometry-and-counting.html"
        },
        {
          "title": "Building the conditional space",
          "href": "lessons/0030-building-the-conditional-space.html"
        },
        {
          "title": "Conditioning in practice",
          "href": "lessons/0031-conditioning-in-practice.html"
        },
        {
          "title": "Pairwise versus mutual independence",
          "href": "lessons/0032-pairwise-versus-mutual.html"
        },
        {
          "title": "The fast track: recap",
          "href": "lessons/0033-the-fast-track-recap.html"
        }
      ]
    },
    {
      "n": "HW1",
      "title": "Homework 1: Practice Set 1, explained",
      "lessons": [
        {
          "title": "Practice: independence and conditioning",
          "href": "lessons/0039-practice-independence-and-conditioning.html"
        },
        {
          "title": "Practice: counting and arrangements",
          "href": "lessons/0040-practice-counting-and-arrangements.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Lecture 1 Formula Sheet",
      "href": "reference/lecture-1-formula-sheet.html"
    },
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    },
    {
      "title": "Lecture 3 Formula Sheet",
      "href": "reference/lecture-3-formula-sheet.html"
    }
  ]
};
