/* Generated by scripts/gen_outline.py from this course's index.html.
   The index page is the source of truth. Re-run the generator after
   adding a lesson; validate_site.py fails the pull request if this
   file and the index disagree. */
window.COURSE_OUTLINE = {
  "key": "llm-papers",
  "title": "LLM Papers, In Order",
  "sections": [
    {
      "n": "00",
      "title": "Foundations",
      "lessons": [
        {
          "title": "Primer: From Neural Nets to Tokens",
          "href": "lessons/0000-primer-neural-nets-to-tokens.html"
        }
      ]
    },
    {
      "n": "01",
      "title": "The Transformer Core",
      "lessons": [
        {
          "title": "Attention Is All You Need",
          "href": "lessons/0001-attention-is-all-you-need.html"
        },
        {
          "title": "BERT",
          "href": "lessons/0002-bert.html"
        },
        {
          "title": "GPT-1: Generative Pre-Training",
          "href": "lessons/0003-gpt-1.html"
        },
        {
          "title": "GPT-2: Scaling + Zero-Shot",
          "href": "lessons/0004-gpt-2.html"
        }
      ]
    },
    {
      "n": "02",
      "title": "Scaling & Data",
      "lessons": [
        {
          "title": "Scaling Laws for Neural LMs",
          "href": "lessons/0005-scaling-laws.html"
        },
        {
          "title": "GPT-3: Few-Shot Learning",
          "href": "lessons/0006-gpt-3.html"
        },
        {
          "title": "The Pile",
          "href": "lessons/0007-the-pile.html"
        },
        {
          "title": "Chinchilla: Compute-Optimal",
          "href": "lessons/0008-chinchilla.html"
        }
      ]
    },
    {
      "n": "03",
      "title": "Big & Open Models",
      "lessons": [
        {
          "title": "PaLM",
          "href": "lessons/0009-palm.html"
        },
        {
          "title": "OPT",
          "href": "lessons/0010-opt.html"
        },
        {
          "title": "BLOOM",
          "href": "lessons/0011-bloom.html"
        },
        {
          "title": "LLaMA",
          "href": "lessons/0012-llama.html"
        }
      ]
    },
    {
      "n": "04",
      "title": "Attention & Position Refinements",
      "lessons": [
        {
          "title": "RoPE: Rotary Position Embeddings",
          "href": "lessons/0013-rope.html"
        },
        {
          "title": "ALiBi",
          "href": "lessons/0014-alibi.html"
        },
        {
          "title": "Multi-Query Attention",
          "href": "lessons/0015-multi-query-attention.html"
        },
        {
          "title": "Grouped-Query Attention",
          "href": "lessons/0016-grouped-query-attention.html"
        }
      ]
    },
    {
      "n": "05",
      "title": "Efficient Inference & Systems",
      "lessons": [
        {
          "title": "FlashAttention",
          "href": "lessons/0017-flashattention.html"
        },
        {
          "title": "FlashAttention-2",
          "href": "lessons/0018-flashattention-2.html"
        },
        {
          "title": "KV Cache Compression",
          "href": "lessons/0019-kv-cache-optimization.html"
        },
        {
          "title": "PagedAttention (vLLM)",
          "href": "lessons/0020-pagedattention-vllm.html"
        },
        {
          "title": "Speculative Decoding",
          "href": "lessons/0021-speculative-decoding.html"
        }
      ]
    },
    {
      "n": "06",
      "title": "Alignment & Post-Training",
      "lessons": [
        {
          "title": "Self-Instruct",
          "href": "lessons/0022-self-instruct.html"
        },
        {
          "title": "InstructGPT (RLHF)",
          "href": "lessons/0023-instructgpt-rlhf.html"
        },
        {
          "title": "Constitutional AI",
          "href": "lessons/0024-constitutional-ai.html"
        },
        {
          "title": "Direct Preference Optimization",
          "href": "lessons/0025-dpo.html"
        },
        {
          "title": "ORPO",
          "href": "lessons/0026-orpo.html"
        },
        {
          "title": "GRPO",
          "href": "lessons/0027-grpo.html"
        }
      ]
    },
    {
      "n": "07",
      "title": "Parameter-Efficient Fine-Tuning",
      "lessons": [
        {
          "title": "LoRA",
          "href": "lessons/0028-lora.html"
        },
        {
          "title": "QLoRA",
          "href": "lessons/0029-qlora.html"
        }
      ]
    },
    {
      "n": "08",
      "title": "Reasoning, Retrieval & Agents",
      "lessons": [
        {
          "title": "Chain-of-Thought Prompting",
          "href": "lessons/0030-chain-of-thought.html"
        },
        {
          "title": "Retrieval-Augmented Generation",
          "href": "lessons/0031-rag.html"
        },
        {
          "title": "ReAct",
          "href": "lessons/0032-react.html"
        },
        {
          "title": "Tree of Thoughts",
          "href": "lessons/0033-tree-of-thoughts.html"
        },
        {
          "title": "Test-Time Scaling",
          "href": "lessons/0034-test-time-scaling.html"
        }
      ]
    },
    {
      "n": "09",
      "title": "Mixture of Experts",
      "lessons": [
        {
          "title": "Switch Transformer (MoE)",
          "href": "lessons/0035-switch-transformer-moe.html"
        },
        {
          "title": "DeepSeekMoE",
          "href": "lessons/0036-deepseekmoe.html"
        }
      ]
    },
    {
      "n": "10",
      "title": "Frontier Optimization",
      "lessons": [
        {
          "title": "Muon Optimizer",
          "href": "lessons/0037-muon-optimizer.html"
        }
      ]
    },
    {
      "n": "11",
      "title": "Vision, Multimodal & Generative",
      "lessons": [
        {
          "title": "Vision Transformer (ViT)",
          "href": "lessons/0038-vision-transformer.html"
        },
        {
          "title": "CLIP",
          "href": "lessons/0039-clip.html"
        },
        {
          "title": "Variational Autoencoders (VAE)",
          "href": "lessons/0040-vae.html"
        },
        {
          "title": "Generative Adversarial Networks",
          "href": "lessons/0041-gan.html"
        },
        {
          "title": "Diffusion Models",
          "href": "lessons/0042-diffusion.html"
        },
        {
          "title": "Primer",
          "href": "lessons/0000-primer-neural-nets-to-tokens.html"
        }
      ]
    }
  ],
  "extras": [
    {
      "title": "Glossary",
      "href": "reference/glossary.html"
    }
  ]
};
